# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

language: rust
sudo: required

rust:
  - stable
  # - beta
  - nightly

env:
  - RELEASE_BUILD=--release
  - RELEASE_BUILD=

before_install:
  - sudo apt update && sudo apt install -y libgl1-mesa-dev cmake libsdl2-dev libgtk-3-dev
  - rustup self update

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo build $RELEASE_BUILD --verbose
  - cargo test $RELEASE_BUILD --verbose

jobs:
  include:
  - stage: lint
    before_install: 
      - rustup component add clippy
      - rustup component add rustfmt
    script: cargo fmt -- --check 
  - stage: nes-web
    before_install:
      - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      - sudo apt install nodejs
    install: "npm install"
    script:
      - npm run build-wasm
      - npm run build

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

deploy:
  local_dir: "nes-web/www/dist/"
  provider: pages
  target_branch: "gh-pages"
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  on:
    condition: -d nes-web/www/dist/
    branch: master
    
notifications:
  email:
    on_success: never
