# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
services: docker
sudo: required

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_install:
  - sudo apt update && sudo apt install -y libgl1-mesa-dev cmake
  - rustup self update

matrix:
  jobs:
    include:
      - stage: "Debug"
        script: 
        - cargo build --all --verbose
        - cargo test --all --verbose
        - cargo fmt --all --verbose -- --check 
      - stage: "Release"
        script: 
        - cargo build --all --release --verbose
        - cargo test --all --release --verbose
        - cargo fmt --all --release --verbose -- --check 

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
