[workspace]
members = [
    "nes-core",
    "nes-standalone",
    "nes-web",
    "nes-test-suite",
    "benchmarks"
]
default-members = ["nes-*"]

[profile.dev]
opt-level = 3

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
