name: CI

on: [push]

jobs:
  build:
    
    strategy:
      matrix:
        toolchain: ['stable', 'beta', 'nightly']
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    
    steps:
    - uses: actions/checkout@v1 
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Lint
      run: cargo fmt -- --check
