use crate::cpu::address_mode::AddressMode;

pub struct Instruction {
    pub opcode: u8,
    pub illegal: bool,

    pub name: &'static str,
    pub description: &'static str,

    pub addressing_mode: AddressMode,

    pub size: u8,
    pub ticks: u8,
    pub page_cross_add: u8,
}

impl Instruction {
    pub fn get_instruction(opcode: u8) -> Instruction {
        match opcode {
            0 => Instruction {
                opcode: 0,
                illegal: false,
                name: "BRK",
                description: "Interrupt",
                addressing_mode: AddressMode::Implied,
                size: 1,
                ticks: 7,
                page_cross_add: 0,
            },
            1 => Instruction {
                opcode: 1,
                illegal: false,
                name: "ORA",
                description: "Or with accumulator",
                addressing_mode: AddressMode::IndirectX,
                size: 2,
                ticks: 6,
                page_cross_add: 0,
            },
            2 => Instruction {
                opcode: 2,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            3 => Instruction {
                opcode: 3,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            4 => Instruction {
                opcode: 4,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            5 => Instruction {
                opcode: 5,
                illegal: false,
                name: "ORA",
                description: "Or with accumulator",
                addressing_mode: AddressMode::Zeropage,
                size: 2,
                ticks: 3,
                page_cross_add: 0,
            },
            6 => Instruction {
                opcode: 6,
                illegal: false,
                name: "ASL",
                description: "Arithmetic shift left",
                addressing_mode: AddressMode::Zeropage,
                size: 2,
                ticks: 5,
                page_cross_add: 0,
            },
            7 => Instruction {
                opcode: 7,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            8 => Instruction {
                opcode: 8,
                illegal: false,
                name: "PHP",
                description: "Push processor status (SR)",
                addressing_mode: AddressMode::Implied,
                size: 1,
                ticks: 3,
                page_cross_add: 0,
            },
            9 => Instruction {
                opcode: 9,
                illegal: false,
                name: "ORA",
                description: "Or with accumulator",
                addressing_mode: AddressMode::Immediate,
                size: 2,
                ticks: 2,
                page_cross_add: 0,
            },
            10 => Instruction {
                opcode: 10,
                illegal: false,
                name: "ASL",
                description: "Arithmetic shift left",
                addressing_mode: AddressMode::Accumulator,
                size: 1,
                ticks: 2,
                page_cross_add: 0,
            },
            11 => Instruction {
                opcode: 11,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            12 => Instruction {
                opcode: 12,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            13 => Instruction {
                opcode: 13,
                illegal: false,
                name: "ORA",
                description: "Or with accumulator",
                addressing_mode: AddressMode::Absolute,
                size: 3,
                ticks: 4,
                page_cross_add: 0,
            },
            14 => Instruction {
                opcode: 14,
                illegal: false,
                name: "ASL",
                description: "Arithmetic shift left",
                addressing_mode: AddressMode::Absolute,
                size: 3,
                ticks: 6,
                page_cross_add: 0,
            },
            15 => Instruction {
                opcode: 15,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            16 => Instruction {
                opcode: 16,
                illegal: false,
                name: "BPL",
                description: "Branch on plus (negative clear)",
                addressing_mode: AddressMode::Relative,
                size: 2,
                ticks: 2,
                page_cross_add: 1,
            },
            17 => Instruction {
                opcode: 17,
                illegal: false,
                name: "ORA",
                description: "Or with accumulator",
                addressing_mode: AddressMode::IndirectY,
                size: 2,
                ticks: 5,
                page_cross_add: 1,
            },
            18 => Instruction {
                opcode: 18,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            19 => Instruction {
                opcode: 19,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            20 => Instruction {
                opcode: 20,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            21 => Instruction {
                opcode: 21,
                illegal: false,
                name: "ORA",
                description: "Or with accumulator",
                addressing_mode: AddressMode::ZeropageX,
                size: 2,
                ticks: 4,
                page_cross_add: 0,
            },
            22 => Instruction {
                opcode: 22,
                illegal: false,
                name: "ASL",
                description: "Arithmetic shift left",
                addressing_mode: AddressMode::ZeropageX,
                size: 2,
                ticks: 6,
                page_cross_add: 0,
            },
            23 => Instruction {
                opcode: 23,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            24 => Instruction {
                opcode: 24,
                illegal: false,
                name: "CLC",
                description: "Clear carry",
                addressing_mode: AddressMode::Implied,
                size: 1,
                ticks: 2,
                page_cross_add: 0,
            },
            25 => Instruction {
                opcode: 25,
                illegal: false,
                name: "ORA",
                description: "Or with accumulator",
                addressing_mode: AddressMode::AbsoluteY,
                size: 3,
                ticks: 4,
                page_cross_add: 1,
            },
            26 => Instruction {
                opcode: 26,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            27 => Instruction {
                opcode: 27,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            28 => Instruction {
                opcode: 28,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            29 => Instruction {
                opcode: 29,
                illegal: false,
                name: "ORA",
                description: "Or with accumulator",
                addressing_mode: AddressMode::AbsoluteX,
                size: 3,
                ticks: 4,
                page_cross_add: 1,
            },
            30 => Instruction {
                opcode: 30,
                illegal: false,
                name: "ASL",
                description: "Arithmetic shift left",
                addressing_mode: AddressMode::AbsoluteX,
                size: 3,
                ticks: 7,
                page_cross_add: 0,
            },
            31 => Instruction {
                opcode: 31,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            32 => Instruction {
                opcode: 32,
                illegal: false,
                name: "JSR",
                description: "Jump subroutine",
                addressing_mode: AddressMode::Absolute,
                size: 3,
                ticks: 6,
                page_cross_add: 0,
            },
            33 => Instruction {
                opcode: 33,
                illegal: false,
                name: "AND",
                description: "And (with accumulator)",
                addressing_mode: AddressMode::IndirectX,
                size: 2,
                ticks: 6,
                page_cross_add: 0,
            },
            34 => Instruction {
                opcode: 34,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            35 => Instruction {
                opcode: 35,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            36 => Instruction {
                opcode: 36,
                illegal: false,
                name: "BIT",
                description: "Bit test",
                addressing_mode: AddressMode::Zeropage,
                size: 2,
                ticks: 3,
                page_cross_add: 0,
            },
            37 => Instruction {
                opcode: 37,
                illegal: false,
                name: "AND",
                description: "And (with accumulator)",
                addressing_mode: AddressMode::Zeropage,
                size: 2,
                ticks: 3,
                page_cross_add: 0,
            },
            38 => Instruction {
                opcode: 38,
                illegal: false,
                name: "ROL",
                description: "Rotate left",
                addressing_mode: AddressMode::Zeropage,
                size: 2,
                ticks: 5,
                page_cross_add: 0,
            },
            39 => Instruction {
                opcode: 39,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            40 => Instruction {
                opcode: 40,
                illegal: false,
                name: "PLP",
                description: "Pull processor status (SR)",
                addressing_mode: AddressMode::Implied,
                size: 1,
                ticks: 4,
                page_cross_add: 0,
            },
            41 => Instruction {
                opcode: 41,
                illegal: false,
                name: "AND",
                description: "And (with accumulator)",
                addressing_mode: AddressMode::Immediate,
                size: 2,
                ticks: 2,
                page_cross_add: 0,
            },
            42 => Instruction {
                opcode: 42,
                illegal: false,
                name: "ROL",
                description: "Rotate left",
                addressing_mode: AddressMode::Accumulator,
                size: 1,
                ticks: 2,
                page_cross_add: 0,
            },
            43 => Instruction {
                opcode: 43,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            44 => Instruction {
                opcode: 44,
                illegal: false,
                name: "BIT",
                description: "Bit test",
                addressing_mode: AddressMode::Absolute,
                size: 3,
                ticks: 4,
                page_cross_add: 0,
            },
            45 => Instruction {
                opcode: 45,
                illegal: false,
                name: "AND",
                description: "And (with accumulator)",
                addressing_mode: AddressMode::Absolute,
                size: 3,
                ticks: 4,
                page_cross_add: 0,
            },
            46 => Instruction {
                opcode: 46,
                illegal: false,
                name: "ROL",
                description: "Rotate left",
                addressing_mode: AddressMode::Absolute,
                size: 3,
                ticks: 6,
                page_cross_add: 0,
            },
            47 => Instruction {
                opcode: 47,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            48 => Instruction {
                opcode: 48,
                illegal: false,
                name: "BMI",
                description: "Branch on minus (negative set)",
                addressing_mode: AddressMode::Relative,
                size: 2,
                ticks: 2,
                page_cross_add: 1,
            },
            49 => Instruction {
                opcode: 49,
                illegal: false,
                name: "AND",
                description: "And (with accumulator)",
                addressing_mode: AddressMode::IndirectY,
                size: 2,
                ticks: 5,
                page_cross_add: 1,
            },
            50 => Instruction {
                opcode: 50,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            51 => Instruction {
                opcode: 51,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            52 => Instruction {
                opcode: 52,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            53 => Instruction {
                opcode: 53,
                illegal: false,
                name: "AND",
                description: "And (with accumulator)",
                addressing_mode: AddressMode::ZeropageX,
                size: 2,
                ticks: 4,
                page_cross_add: 0,
            },
            54 => Instruction {
                opcode: 54,
                illegal: false,
                name: "ROL",
                description: "Rotate left",
                addressing_mode: AddressMode::ZeropageX,
                size: 2,
                ticks: 6,
                page_cross_add: 0,
            },
            55 => Instruction {
                opcode: 55,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            56 => Instruction {
                opcode: 56,
                illegal: false,
                name: "SEC",
                description: "Set carry",
                addressing_mode: AddressMode::Implied,
                size: 1,
                ticks: 2,
                page_cross_add: 0,
            },
            57 => Instruction {
                opcode: 57,
                illegal: false,
                name: "AND",
                description: "And (with accumulator)",
                addressing_mode: AddressMode::AbsoluteY,
                size: 3,
                ticks: 4,
                page_cross_add: 1,
            },
            58 => Instruction {
                opcode: 58,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            59 => Instruction {
                opcode: 59,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            60 => Instruction {
                opcode: 60,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            61 => Instruction {
                opcode: 61,
                illegal: false,
                name: "AND",
                description: "And (with accumulator)",
                addressing_mode: AddressMode::AbsoluteX,
                size: 3,
                ticks: 4,
                page_cross_add: 1,
            },
            62 => Instruction {
                opcode: 62,
                illegal: false,
                name: "ROL",
                description: "Rotate left",
                addressing_mode: AddressMode::AbsoluteX,
                size: 3,
                ticks: 7,
                page_cross_add: 0,
            },
            63 => Instruction {
                opcode: 63,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            64 => Instruction {
                opcode: 64,
                illegal: false,
                name: "RTI",
                description: "Return from interrupt",
                addressing_mode: AddressMode::Implied,
                size: 1,
                ticks: 6,
                page_cross_add: 0,
            },
            65 => Instruction {
                opcode: 65,
                illegal: false,
                name: "EOR",
                description: "Exclusive or (with accumulator)",
                addressing_mode: AddressMode::IndirectX,
                size: 2,
                ticks: 6,
                page_cross_add: 0,
            },
            66 => Instruction {
                opcode: 66,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            67 => Instruction {
                opcode: 67,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            68 => Instruction {
                opcode: 68,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            69 => Instruction {
                opcode: 69,
                illegal: false,
                name: "EOR",
                description: "Exclusive or (with accumulator)",
                addressing_mode: AddressMode::Zeropage,
                size: 2,
                ticks: 3,
                page_cross_add: 0,
            },
            70 => Instruction {
                opcode: 70,
                illegal: false,
                name: "LSR",
                description: "Logical shift right",
                addressing_mode: AddressMode::Zeropage,
                size: 2,
                ticks: 5,
                page_cross_add: 0,
            },
            71 => Instruction {
                opcode: 71,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            72 => Instruction {
                opcode: 72,
                illegal: false,
                name: "PHA",
                description: "Push accumulator",
                addressing_mode: AddressMode::Implied,
                size: 1,
                ticks: 3,
                page_cross_add: 0,
            },
            73 => Instruction {
                opcode: 73,
                illegal: false,
                name: "EOR",
                description: "Exclusive or (with accumulator)",
                addressing_mode: AddressMode::Immediate,
                size: 2,
                ticks: 2,
                page_cross_add: 0,
            },
            74 => Instruction {
                opcode: 74,
                illegal: false,
                name: "LSR",
                description: "Logical shift right",
                addressing_mode: AddressMode::Accumulator,
                size: 1,
                ticks: 2,
                page_cross_add: 0,
            },
            75 => Instruction {
                opcode: 75,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            76 => Instruction {
                opcode: 76,
                illegal: false,
                name: "JMP",
                description: "Jump",
                addressing_mode: AddressMode::Absolute,
                size: 3,
                ticks: 3,
                page_cross_add: 0,
            },
            77 => Instruction {
                opcode: 77,
                illegal: false,
                name: "EOR",
                description: "Exclusive or (with accumulator)",
                addressing_mode: AddressMode::Absolute,
                size: 3,
                ticks: 4,
                page_cross_add: 0,
            },
            78 => Instruction {
                opcode: 78,
                illegal: false,
                name: "LSR",
                description: "Logical shift right",
                addressing_mode: AddressMode::Absolute,
                size: 3,
                ticks: 6,
                page_cross_add: 0,
            },
            79 => Instruction {
                opcode: 79,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            80 => Instruction {
                opcode: 80,
                illegal: false,
                name: "BVC",
                description: "Branch on overflow clear",
                addressing_mode: AddressMode::Relative,
                size: 2,
                ticks: 2,
                page_cross_add: 1,
            },
            81 => Instruction {
                opcode: 81,
                illegal: false,
                name: "EOR",
                description: "Exclusive or (with accumulator)",
                addressing_mode: AddressMode::IndirectY,
                size: 2,
                ticks: 5,
                page_cross_add: 1,
            },
            82 => Instruction {
                opcode: 82,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            83 => Instruction {
                opcode: 83,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            84 => Instruction {
                opcode: 84,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            85 => Instruction {
                opcode: 85,
                illegal: false,
                name: "EOR",
                description: "Exclusive or (with accumulator)",
                addressing_mode: AddressMode::ZeropageX,
                size: 2,
                ticks: 4,
                page_cross_add: 0,
            },
            86 => Instruction {
                opcode: 86,
                illegal: false,
                name: "LSR",
                description: "Logical shift right",
                addressing_mode: AddressMode::ZeropageX,
                size: 2,
                ticks: 6,
                page_cross_add: 0,
            },
            87 => Instruction {
                opcode: 87,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            88 => Instruction {
                opcode: 88,
                illegal: false,
                name: "CLI",
                description: "Clear interrupt disable",
                addressing_mode: AddressMode::Implied,
                size: 1,
                ticks: 2,
                page_cross_add: 0,
            },
            89 => Instruction {
                opcode: 89,
                illegal: false,
                name: "EOR",
                description: "Exclusive or (with accumulator)",
                addressing_mode: AddressMode::AbsoluteY,
                size: 3,
                ticks: 4,
                page_cross_add: 1,
            },
            90 => Instruction {
                opcode: 90,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            91 => Instruction {
                opcode: 91,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            92 => Instruction {
                opcode: 92,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            93 => Instruction {
                opcode: 93,
                illegal: false,
                name: "EOR",
                description: "Exclusive or (with accumulator)",
                addressing_mode: AddressMode::AbsoluteX,
                size: 3,
                ticks: 4,
                page_cross_add: 1,
            },
            94 => Instruction {
                opcode: 94,
                illegal: false,
                name: "LSR",
                description: "Logical shift right",
                addressing_mode: AddressMode::AbsoluteX,
                size: 3,
                ticks: 7,
                page_cross_add: 0,
            },
            95 => Instruction {
                opcode: 95,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            96 => Instruction {
                opcode: 96,
                illegal: false,
                name: "RTS",
                description: "Return from subroutine",
                addressing_mode: AddressMode::Implied,
                size: 1,
                ticks: 6,
                page_cross_add: 0,
            },
            97 => Instruction {
                opcode: 97,
                illegal: false,
                name: "ADC",
                description: "Add with carry",
                addressing_mode: AddressMode::IndirectX,
                size: 2,
                ticks: 6,
                page_cross_add: 0,
            },
            98 => Instruction {
                opcode: 98,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            99 => Instruction {
                opcode: 99,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            100 => Instruction {
                opcode: 100,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            101 => Instruction {
                opcode: 101,
                illegal: false,
                name: "ADC",
                description: "Add with carry",
                addressing_mode: AddressMode::Zeropage,
                size: 2,
                ticks: 3,
                page_cross_add: 0,
            },
            102 => Instruction {
                opcode: 102,
                illegal: false,
                name: "ROR",
                description: "Rotate right",
                addressing_mode: AddressMode::Zeropage,
                size: 2,
                ticks: 5,
                page_cross_add: 0,
            },
            103 => Instruction {
                opcode: 103,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            104 => Instruction {
                opcode: 104,
                illegal: false,
                name: "PLA",
                description: "Pull accumulator",
                addressing_mode: AddressMode::Implied,
                size: 1,
                ticks: 4,
                page_cross_add: 0,
            },
            105 => Instruction {
                opcode: 105,
                illegal: false,
                name: "ADC",
                description: "Add with carry",
                addressing_mode: AddressMode::Immediate,
                size: 2,
                ticks: 2,
                page_cross_add: 0,
            },
            106 => Instruction {
                opcode: 106,
                illegal: false,
                name: "ROR",
                description: "Rotate right",
                addressing_mode: AddressMode::Accumulator,
                size: 1,
                ticks: 2,
                page_cross_add: 0,
            },
            107 => Instruction {
                opcode: 107,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            108 => Instruction {
                opcode: 108,
                illegal: false,
                name: "JMP",
                description: "Jump",
                addressing_mode: AddressMode::Indirect,
                size: 3,
                ticks: 5,
                page_cross_add: 0,
            },
            109 => Instruction {
                opcode: 109,
                illegal: false,
                name: "ADC",
                description: "Add with carry",
                addressing_mode: AddressMode::Absolute,
                size: 3,
                ticks: 4,
                page_cross_add: 0,
            },
            110 => Instruction {
                opcode: 110,
                illegal: false,
                name: "ROR",
                description: "Rotate right",
                addressing_mode: AddressMode::Absolute,
                size: 3,
                ticks: 6,
                page_cross_add: 0,
            },
            111 => Instruction {
                opcode: 111,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            112 => Instruction {
                opcode: 112,
                illegal: false,
                name: "BVS",
                description: "Branch on overflow set",
                addressing_mode: AddressMode::Relative,
                size: 2,
                ticks: 2,
                page_cross_add: 1,
            },
            113 => Instruction {
                opcode: 113,
                illegal: false,
                name: "ADC",
                description: "Add with carry",
                addressing_mode: AddressMode::IndirectY,
                size: 2,
                ticks: 5,
                page_cross_add: 1,
            },
            114 => Instruction {
                opcode: 114,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            115 => Instruction {
                opcode: 115,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            116 => Instruction {
                opcode: 116,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            117 => Instruction {
                opcode: 117,
                illegal: false,
                name: "ADC",
                description: "Add with carry",
                addressing_mode: AddressMode::ZeropageX,
                size: 2,
                ticks: 4,
                page_cross_add: 0,
            },
            118 => Instruction {
                opcode: 118,
                illegal: false,
                name: "ROR",
                description: "Rotate right",
                addressing_mode: AddressMode::ZeropageX,
                size: 2,
                ticks: 6,
                page_cross_add: 0,
            },
            119 => Instruction {
                opcode: 119,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            120 => Instruction {
                opcode: 120,
                illegal: false,
                name: "SEI",
                description: "Set interrupt disable",
                addressing_mode: AddressMode::Implied,
                size: 1,
                ticks: 2,
                page_cross_add: 0,
            },
            121 => Instruction {
                opcode: 121,
                illegal: false,
                name: "ADC",
                description: "Add with carry",
                addressing_mode: AddressMode::AbsoluteY,
                size: 3,
                ticks: 4,
                page_cross_add: 1,
            },
            122 => Instruction {
                opcode: 122,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            123 => Instruction {
                opcode: 123,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            124 => Instruction {
                opcode: 124,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            125 => Instruction {
                opcode: 125,
                illegal: false,
                name: "ADC",
                description: "Add with carry",
                addressing_mode: AddressMode::AbsoluteX,
                size: 3,
                ticks: 4,
                page_cross_add: 1,
            },
            126 => Instruction {
                opcode: 126,
                illegal: false,
                name: "ROR",
                description: "Rotate right",
                addressing_mode: AddressMode::AbsoluteX,
                size: 3,
                ticks: 7,
                page_cross_add: 0,
            },
            127 => Instruction {
                opcode: 127,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            128 => Instruction {
                opcode: 128,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            129 => Instruction {
                opcode: 129,
                illegal: false,
                name: "STA",
                description: "Store accumulator",
                addressing_mode: AddressMode::IndirectX,
                size: 2,
                ticks: 6,
                page_cross_add: 0,
            },
            130 => Instruction {
                opcode: 130,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            131 => Instruction {
                opcode: 131,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            132 => Instruction {
                opcode: 132,
                illegal: false,
                name: "STY",
                description: "Store Y",
                addressing_mode: AddressMode::Zeropage,
                size: 2,
                ticks: 3,
                page_cross_add: 0,
            },
            133 => Instruction {
                opcode: 133,
                illegal: false,
                name: "STA",
                description: "Store accumulator",
                addressing_mode: AddressMode::Zeropage,
                size: 2,
                ticks: 3,
                page_cross_add: 0,
            },
            134 => Instruction {
                opcode: 134,
                illegal: false,
                name: "STX",
                description: "Store X",
                addressing_mode: AddressMode::Zeropage,
                size: 2,
                ticks: 3,
                page_cross_add: 0,
            },
            135 => Instruction {
                opcode: 135,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            136 => Instruction {
                opcode: 136,
                illegal: false,
                name: "DEY",
                description: "Decrement Y",
                addressing_mode: AddressMode::Implied,
                size: 1,
                ticks: 2,
                page_cross_add: 0,
            },
            137 => Instruction {
                opcode: 137,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            138 => Instruction {
                opcode: 138,
                illegal: false,
                name: "TXA",
                description: "Transfer X to accumulator",
                addressing_mode: AddressMode::Implied,
                size: 1,
                ticks: 2,
                page_cross_add: 0,
            },
            139 => Instruction {
                opcode: 139,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            140 => Instruction {
                opcode: 140,
                illegal: false,
                name: "STY",
                description: "Store Y",
                addressing_mode: AddressMode::Absolute,
                size: 3,
                ticks: 4,
                page_cross_add: 0,
            },
            141 => Instruction {
                opcode: 141,
                illegal: false,
                name: "STA",
                description: "Store accumulator",
                addressing_mode: AddressMode::Absolute,
                size: 3,
                ticks: 4,
                page_cross_add: 0,
            },
            142 => Instruction {
                opcode: 142,
                illegal: false,
                name: "STX",
                description: "Store X",
                addressing_mode: AddressMode::Absolute,
                size: 3,
                ticks: 4,
                page_cross_add: 0,
            },
            143 => Instruction {
                opcode: 143,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            144 => Instruction {
                opcode: 144,
                illegal: false,
                name: "BCC",
                description: "Branch on carry clear",
                addressing_mode: AddressMode::Relative,
                size: 2,
                ticks: 2,
                page_cross_add: 1,
            },
            145 => Instruction {
                opcode: 145,
                illegal: false,
                name: "STA",
                description: "Store accumulator",
                addressing_mode: AddressMode::IndirectY,
                size: 2,
                ticks: 6,
                page_cross_add: 0,
            },
            146 => Instruction {
                opcode: 146,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            147 => Instruction {
                opcode: 147,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            148 => Instruction {
                opcode: 148,
                illegal: false,
                name: "STY",
                description: "Store Y",
                addressing_mode: AddressMode::ZeropageX,
                size: 2,
                ticks: 4,
                page_cross_add: 0,
            },
            149 => Instruction {
                opcode: 149,
                illegal: false,
                name: "STA",
                description: "Store accumulator",
                addressing_mode: AddressMode::ZeropageX,
                size: 2,
                ticks: 4,
                page_cross_add: 0,
            },
            150 => Instruction {
                opcode: 150,
                illegal: false,
                name: "STX",
                description: "Store X",
                addressing_mode: AddressMode::ZeropageY,
                size: 2,
                ticks: 4,
                page_cross_add: 0,
            },
            151 => Instruction {
                opcode: 151,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            152 => Instruction {
                opcode: 152,
                illegal: false,
                name: "TYA",
                description: "Transfer Y to accumulator",
                addressing_mode: AddressMode::Implied,
                size: 1,
                ticks: 2,
                page_cross_add: 0,
            },
            153 => Instruction {
                opcode: 153,
                illegal: false,
                name: "STA",
                description: "Store accumulator",
                addressing_mode: AddressMode::AbsoluteY,
                size: 3,
                ticks: 5,
                page_cross_add: 0,
            },
            154 => Instruction {
                opcode: 154,
                illegal: false,
                name: "TXS",
                description: "Transfer X to stack pointer",
                addressing_mode: AddressMode::Implied,
                size: 1,
                ticks: 2,
                page_cross_add: 0,
            },
            155 => Instruction {
                opcode: 155,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            156 => Instruction {
                opcode: 156,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            157 => Instruction {
                opcode: 157,
                illegal: false,
                name: "STA",
                description: "Store accumulator",
                addressing_mode: AddressMode::AbsoluteX,
                size: 3,
                ticks: 5,
                page_cross_add: 0,
            },
            158 => Instruction {
                opcode: 158,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            159 => Instruction {
                opcode: 159,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            160 => Instruction {
                opcode: 160,
                illegal: false,
                name: "LDY",
                description: "Load Y",
                addressing_mode: AddressMode::Immediate,
                size: 2,
                ticks: 2,
                page_cross_add: 0,
            },
            161 => Instruction {
                opcode: 161,
                illegal: false,
                name: "LDA",
                description: "Load accumulator",
                addressing_mode: AddressMode::IndirectX,
                size: 2,
                ticks: 6,
                page_cross_add: 0,
            },
            162 => Instruction {
                opcode: 162,
                illegal: false,
                name: "LDX",
                description: "Load X",
                addressing_mode: AddressMode::Immediate,
                size: 2,
                ticks: 2,
                page_cross_add: 0,
            },
            163 => Instruction {
                opcode: 163,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            164 => Instruction {
                opcode: 164,
                illegal: false,
                name: "LDY",
                description: "Load Y",
                addressing_mode: AddressMode::Zeropage,
                size: 2,
                ticks: 3,
                page_cross_add: 0,
            },
            165 => Instruction {
                opcode: 165,
                illegal: false,
                name: "LDA",
                description: "Load accumulator",
                addressing_mode: AddressMode::Zeropage,
                size: 2,
                ticks: 3,
                page_cross_add: 0,
            },
            166 => Instruction {
                opcode: 166,
                illegal: false,
                name: "LDX",
                description: "Load X",
                addressing_mode: AddressMode::Zeropage,
                size: 2,
                ticks: 3,
                page_cross_add: 0,
            },
            167 => Instruction {
                opcode: 167,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            168 => Instruction {
                opcode: 168,
                illegal: false,
                name: "TAY",
                description: "Transfer accumulator to Y",
                addressing_mode: AddressMode::Implied,
                size: 1,
                ticks: 2,
                page_cross_add: 0,
            },
            169 => Instruction {
                opcode: 169,
                illegal: false,
                name: "LDA",
                description: "Load accumulator",
                addressing_mode: AddressMode::Immediate,
                size: 2,
                ticks: 2,
                page_cross_add: 0,
            },
            170 => Instruction {
                opcode: 170,
                illegal: false,
                name: "TAX",
                description: "Transfer accumulator to X",
                addressing_mode: AddressMode::Implied,
                size: 1,
                ticks: 2,
                page_cross_add: 0,
            },
            171 => Instruction {
                opcode: 171,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            172 => Instruction {
                opcode: 172,
                illegal: false,
                name: "LDY",
                description: "Load Y",
                addressing_mode: AddressMode::Absolute,
                size: 3,
                ticks: 4,
                page_cross_add: 0,
            },
            173 => Instruction {
                opcode: 173,
                illegal: false,
                name: "LDA",
                description: "Load accumulator",
                addressing_mode: AddressMode::Absolute,
                size: 3,
                ticks: 4,
                page_cross_add: 0,
            },
            174 => Instruction {
                opcode: 174,
                illegal: false,
                name: "LDX",
                description: "Load X",
                addressing_mode: AddressMode::Absolute,
                size: 3,
                ticks: 4,
                page_cross_add: 0,
            },
            175 => Instruction {
                opcode: 175,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            176 => Instruction {
                opcode: 176,
                illegal: false,
                name: "BCS",
                description: "Branch on carry set",
                addressing_mode: AddressMode::Relative,
                size: 2,
                ticks: 2,
                page_cross_add: 1,
            },
            177 => Instruction {
                opcode: 177,
                illegal: false,
                name: "LDA",
                description: "Load accumulator",
                addressing_mode: AddressMode::IndirectY,
                size: 2,
                ticks: 5,
                page_cross_add: 1,
            },
            178 => Instruction {
                opcode: 178,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            179 => Instruction {
                opcode: 179,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            180 => Instruction {
                opcode: 180,
                illegal: false,
                name: "LDY",
                description: "Load Y",
                addressing_mode: AddressMode::ZeropageX,
                size: 2,
                ticks: 4,
                page_cross_add: 0,
            },
            181 => Instruction {
                opcode: 181,
                illegal: false,
                name: "LDA",
                description: "Load accumulator",
                addressing_mode: AddressMode::ZeropageX,
                size: 2,
                ticks: 4,
                page_cross_add: 0,
            },
            182 => Instruction {
                opcode: 182,
                illegal: false,
                name: "LDX",
                description: "Load X",
                addressing_mode: AddressMode::ZeropageY,
                size: 2,
                ticks: 4,
                page_cross_add: 0,
            },
            183 => Instruction {
                opcode: 183,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            184 => Instruction {
                opcode: 184,
                illegal: false,
                name: "CLV",
                description: "Clear overflow",
                addressing_mode: AddressMode::Implied,
                size: 1,
                ticks: 2,
                page_cross_add: 0,
            },
            185 => Instruction {
                opcode: 185,
                illegal: false,
                name: "LDA",
                description: "Load accumulator",
                addressing_mode: AddressMode::AbsoluteY,
                size: 3,
                ticks: 4,
                page_cross_add: 1,
            },
            186 => Instruction {
                opcode: 186,
                illegal: false,
                name: "TSX",
                description: "Transfer stack pointer to X",
                addressing_mode: AddressMode::Implied,
                size: 1,
                ticks: 2,
                page_cross_add: 0,
            },
            187 => Instruction {
                opcode: 187,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            188 => Instruction {
                opcode: 188,
                illegal: false,
                name: "LDY",
                description: "Load Y",
                addressing_mode: AddressMode::AbsoluteX,
                size: 3,
                ticks: 4,
                page_cross_add: 1,
            },
            189 => Instruction {
                opcode: 189,
                illegal: false,
                name: "LDA",
                description: "Load accumulator",
                addressing_mode: AddressMode::AbsoluteX,
                size: 3,
                ticks: 4,
                page_cross_add: 1,
            },
            190 => Instruction {
                opcode: 190,
                illegal: false,
                name: "LDX",
                description: "Load X",
                addressing_mode: AddressMode::AbsoluteY,
                size: 3,
                ticks: 4,
                page_cross_add: 1,
            },
            191 => Instruction {
                opcode: 191,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            192 => Instruction {
                opcode: 192,
                illegal: false,
                name: "CPY",
                description: "Compare with Y",
                addressing_mode: AddressMode::Immediate,
                size: 2,
                ticks: 2,
                page_cross_add: 0,
            },
            193 => Instruction {
                opcode: 193,
                illegal: false,
                name: "CMP",
                description: "Compare (with accumulator)",
                addressing_mode: AddressMode::IndirectX,
                size: 2,
                ticks: 6,
                page_cross_add: 0,
            },
            194 => Instruction {
                opcode: 194,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            195 => Instruction {
                opcode: 195,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            196 => Instruction {
                opcode: 196,
                illegal: false,
                name: "CPY",
                description: "Compare with Y",
                addressing_mode: AddressMode::Zeropage,
                size: 2,
                ticks: 3,
                page_cross_add: 0,
            },
            197 => Instruction {
                opcode: 197,
                illegal: false,
                name: "CMP",
                description: "Compare (with accumulator)",
                addressing_mode: AddressMode::Zeropage,
                size: 2,
                ticks: 3,
                page_cross_add: 0,
            },
            198 => Instruction {
                opcode: 198,
                illegal: false,
                name: "DEC",
                description: "Decrement",
                addressing_mode: AddressMode::Zeropage,
                size: 2,
                ticks: 5,
                page_cross_add: 0,
            },
            199 => Instruction {
                opcode: 199,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            200 => Instruction {
                opcode: 200,
                illegal: false,
                name: "INY",
                description: "Increment Y",
                addressing_mode: AddressMode::Implied,
                size: 1,
                ticks: 2,
                page_cross_add: 0,
            },
            201 => Instruction {
                opcode: 201,
                illegal: false,
                name: "CMP",
                description: "Compare (with accumulator)",
                addressing_mode: AddressMode::Immediate,
                size: 2,
                ticks: 2,
                page_cross_add: 0,
            },
            202 => Instruction {
                opcode: 202,
                illegal: false,
                name: "DEX",
                description: "Decrement X",
                addressing_mode: AddressMode::Implied,
                size: 1,
                ticks: 2,
                page_cross_add: 0,
            },
            203 => Instruction {
                opcode: 203,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            204 => Instruction {
                opcode: 204,
                illegal: false,
                name: "CPY",
                description: "Compare with Y",
                addressing_mode: AddressMode::Absolute,
                size: 3,
                ticks: 4,
                page_cross_add: 0,
            },
            205 => Instruction {
                opcode: 205,
                illegal: false,
                name: "CMP",
                description: "Compare (with accumulator)",
                addressing_mode: AddressMode::Absolute,
                size: 3,
                ticks: 4,
                page_cross_add: 0,
            },
            206 => Instruction {
                opcode: 206,
                illegal: false,
                name: "DEC",
                description: "Decrement",
                addressing_mode: AddressMode::Absolute,
                size: 3,
                ticks: 3,
                page_cross_add: 0,
            },
            207 => Instruction {
                opcode: 207,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            208 => Instruction {
                opcode: 208,
                illegal: false,
                name: "BNE",
                description: "Branch on not equal (zero clear)",
                addressing_mode: AddressMode::Relative,
                size: 2,
                ticks: 2,
                page_cross_add: 1,
            },
            209 => Instruction {
                opcode: 209,
                illegal: false,
                name: "CMP",
                description: "Compare (with accumulator)",
                addressing_mode: AddressMode::IndirectY,
                size: 2,
                ticks: 5,
                page_cross_add: 1,
            },
            210 => Instruction {
                opcode: 210,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            211 => Instruction {
                opcode: 211,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            212 => Instruction {
                opcode: 212,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            213 => Instruction {
                opcode: 213,
                illegal: false,
                name: "CMP",
                description: "Compare (with accumulator)",
                addressing_mode: AddressMode::ZeropageX,
                size: 2,
                ticks: 4,
                page_cross_add: 0,
            },
            214 => Instruction {
                opcode: 214,
                illegal: false,
                name: "DEC",
                description: "Decrement",
                addressing_mode: AddressMode::ZeropageX,
                size: 2,
                ticks: 6,
                page_cross_add: 0,
            },
            215 => Instruction {
                opcode: 215,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            216 => Instruction {
                opcode: 216,
                illegal: false,
                name: "CLD",
                description: "Clear decimal",
                addressing_mode: AddressMode::Implied,
                size: 1,
                ticks: 2,
                page_cross_add: 0,
            },
            217 => Instruction {
                opcode: 217,
                illegal: false,
                name: "CMP",
                description: "Compare (with accumulator)",
                addressing_mode: AddressMode::AbsoluteY,
                size: 3,
                ticks: 4,
                page_cross_add: 1,
            },
            218 => Instruction {
                opcode: 218,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            219 => Instruction {
                opcode: 219,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            220 => Instruction {
                opcode: 220,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            221 => Instruction {
                opcode: 221,
                illegal: false,
                name: "CMP",
                description: "Compare (with accumulator)",
                addressing_mode: AddressMode::AbsoluteX,
                size: 3,
                ticks: 4,
                page_cross_add: 1,
            },
            222 => Instruction {
                opcode: 222,
                illegal: false,
                name: "DEC",
                description: "Decrement",
                addressing_mode: AddressMode::AbsoluteX,
                size: 3,
                ticks: 7,
                page_cross_add: 0,
            },
            223 => Instruction {
                opcode: 223,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            224 => Instruction {
                opcode: 224,
                illegal: false,
                name: "CPX",
                description: "Compare with X",
                addressing_mode: AddressMode::Immediate,
                size: 2,
                ticks: 2,
                page_cross_add: 0,
            },
            225 => Instruction {
                opcode: 225,
                illegal: false,
                name: "SBC",
                description: "Subtract with carry",
                addressing_mode: AddressMode::IndirectX,
                size: 2,
                ticks: 6,
                page_cross_add: 0,
            },
            226 => Instruction {
                opcode: 226,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            227 => Instruction {
                opcode: 227,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            228 => Instruction {
                opcode: 228,
                illegal: false,
                name: "CPX",
                description: "Compare with X",
                addressing_mode: AddressMode::Zeropage,
                size: 2,
                ticks: 3,
                page_cross_add: 0,
            },
            229 => Instruction {
                opcode: 229,
                illegal: false,
                name: "SBC",
                description: "Subtract with carry",
                addressing_mode: AddressMode::Zeropage,
                size: 2,
                ticks: 3,
                page_cross_add: 0,
            },
            230 => Instruction {
                opcode: 230,
                illegal: false,
                name: "INC",
                description: "Increment",
                addressing_mode: AddressMode::Zeropage,
                size: 2,
                ticks: 5,
                page_cross_add: 0,
            },
            231 => Instruction {
                opcode: 231,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            232 => Instruction {
                opcode: 232,
                illegal: false,
                name: "INX",
                description: "Increment X",
                addressing_mode: AddressMode::Implied,
                size: 1,
                ticks: 2,
                page_cross_add: 0,
            },
            233 => Instruction {
                opcode: 233,
                illegal: false,
                name: "SBC",
                description: "Subtract with carry",
                addressing_mode: AddressMode::Immediate,
                size: 2,
                ticks: 2,
                page_cross_add: 0,
            },
            234 => Instruction {
                opcode: 234,
                illegal: false,
                name: "NOP",
                description: "No operation",
                addressing_mode: AddressMode::Implied,
                size: 1,
                ticks: 2,
                page_cross_add: 0,
            },
            235 => Instruction {
                opcode: 235,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            236 => Instruction {
                opcode: 236,
                illegal: false,
                name: "CPX",
                description: "Compare with X",
                addressing_mode: AddressMode::Absolute,
                size: 3,
                ticks: 4,
                page_cross_add: 0,
            },
            237 => Instruction {
                opcode: 237,
                illegal: false,
                name: "SBC",
                description: "Subtract with carry",
                addressing_mode: AddressMode::Absolute,
                size: 3,
                ticks: 4,
                page_cross_add: 0,
            },
            238 => Instruction {
                opcode: 238,
                illegal: false,
                name: "INC",
                description: "Increment",
                addressing_mode: AddressMode::Absolute,
                size: 3,
                ticks: 6,
                page_cross_add: 0,
            },
            239 => Instruction {
                opcode: 239,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            240 => Instruction {
                opcode: 240,
                illegal: false,
                name: "BEQ",
                description: "Branch on equal (zero set)",
                addressing_mode: AddressMode::Relative,
                size: 2,
                ticks: 2,
                page_cross_add: 1,
            },
            241 => Instruction {
                opcode: 241,
                illegal: false,
                name: "SBC",
                description: "Subtract with carry",
                addressing_mode: AddressMode::IndirectY,
                size: 2,
                ticks: 5,
                page_cross_add: 1,
            },
            242 => Instruction {
                opcode: 242,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            243 => Instruction {
                opcode: 243,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            244 => Instruction {
                opcode: 244,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            245 => Instruction {
                opcode: 245,
                illegal: false,
                name: "SBC",
                description: "Subtract with carry",
                addressing_mode: AddressMode::ZeropageX,
                size: 2,
                ticks: 4,
                page_cross_add: 0,
            },
            246 => Instruction {
                opcode: 246,
                illegal: false,
                name: "INC",
                description: "Increment",
                addressing_mode: AddressMode::ZeropageX,
                size: 2,
                ticks: 6,
                page_cross_add: 0,
            },
            247 => Instruction {
                opcode: 247,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            248 => Instruction {
                opcode: 248,
                illegal: false,
                name: "SED",
                description: "Set decimal",
                addressing_mode: AddressMode::Implied,
                size: 1,
                ticks: 2,
                page_cross_add: 0,
            },
            249 => Instruction {
                opcode: 249,
                illegal: false,
                name: "SBC",
                description: "Subtract with carry",
                addressing_mode: AddressMode::AbsoluteY,
                size: 3,
                ticks: 4,
                page_cross_add: 1,
            },
            250 => Instruction {
                opcode: 250,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            251 => Instruction {
                opcode: 251,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            252 => Instruction {
                opcode: 252,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
            253 => Instruction {
                opcode: 253,
                illegal: false,
                name: "SBC",
                description: "Subtract with carry",
                addressing_mode: AddressMode::AbsoluteX,
                size: 3,
                ticks: 4,
                page_cross_add: 1,
            },
            254 => Instruction {
                opcode: 254,
                illegal: false,
                name: "INC",
                description: "Increment",
                addressing_mode: AddressMode::AbsoluteX,
                size: 3,
                ticks: 7,
                page_cross_add: 0,
            },
            255 => Instruction {
                opcode: 255,
                illegal: true,
                name: "???",
                description: "",
                addressing_mode: AddressMode::Unknown,
                size: 255,
                ticks: 255,
                page_cross_add: 255,
            },
        }
    }
}
