[package]
name = "nes-core"
version = "0.1.0"
authors = ["muka"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.1"

[dev-dependencies]
